name: CI Pipeline

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install uv
      run: pip install uv

    - name: Install dependencies
      run: uv pip install --system .

    - name: Install lint tools
      run: uv pip install black isort flake8

    - name: Run Black
      run: uv run black --check .

    - name: Run isort
      run: uv run isort --check-only .

    - name: Run Flake8
      run: uv run flake8 .